//! The Finding type — the primary output contract between research-radar and evolve.
//!
//! A `Finding` is a research result with enough structure for evolve to make a
//! go/no-go decision on whether to generate a code change. It is not a raw
//! annotation or summary — it is a evaluated, prioritized signal.
//!
//! ## Design principles
//!
//! - **evolvable**: schema_version allows the Finding format to evolve without
//!   breaking existing consumers.
//! - **decisive**: impact_weight and urgency give evolve a clear prioritization
//!   signal so it doesn't treat a CVE the same as an architectural pattern.
//! - **cited**: every Finding carries a PaperRef when available, making every
//!   evolve PR a citable change.
//! - **actionable**: suggested_action is a high-level intent string, not a diff.
//!   The diff is generated by evolve given the intent + applicability search.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ─── UrgencyLevel ────────────────────────────────────────────────────────────

/// How urgently this finding should be acted on.
///
/// Used by evolve to prioritize its PR queue and by humans reviewing the queue.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum UrgencyLevel {
    /// Nice-to-have. Architectural pattern, quality-of-life improvement.
    Low,
    /// Worth acting on in the normal course. Not a fire.
    Medium,
    /// Significant issue or opportunity. Should be addressed soon.
    High,
    /// CVE, security regression, or data loss risk. Drop everything.
    Critical,
}

impl UrgencyLevel {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Low => "low",
            Self::Medium => "medium",
            Self::High => "high",
            Self::Critical => "critical",
        }
    }

    // Intentional inherent parser: infallible and returns Self, distinct from std::str::FromStr.
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(s: &str) -> Self {
        match s {
            "low" => Self::Low,
            "medium" => Self::Medium,
            "high" => Self::High,
            "critical" => Self::Critical,
            _ => Self::Medium,
        }
    }

    /// True if this urgency level should block normal operations.
    pub fn is_critical(&self) -> bool {
        matches!(self, Self::Critical)
    }
}

impl std::fmt::Display for UrgencyLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// ─── PaperRef ──────────────────────────────────────────────────────────────

/// A formal academic or authoritative source citation.
///
/// Included when the finding is derived from a paper, RFC, or other citable work.
/// This is what makes an evolve PR a cited document rather than a random change.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaperRef {
    /// Full title of the paper or article.
    pub title: String,
    /// Comma-separated author names. E.g. "Carl Hensel, Patrik Wirth"
    pub authors: String,
    /// Year of publication.
    pub year: Option<u16>,
    /// URL to the paper, preprint, or official source.
    pub url: String,
    /// Conference, journal, or venue name (optional).
    pub venue: Option<String>,
}

impl PaperRef {
    /// Construct a new PaperRef. year and venue are optional.
    pub fn new(title: String, authors: String, url: String) -> Self {
        Self {
            title,
            authors,
            year: None,
            url,
            venue: None,
        }
    }

    /// Full citation string for use in PR descriptions.
    ///
    /// Format: "{title}" by {authors} ({year}). {url}
    /// Falls back gracefully when year or venue is absent.
    pub fn citation(&self) -> String {
        let year_str = self
            .year
            .map(|y| y.to_string())
            .unwrap_or_else(|| "n.d.".into());
        match &self.venue {
            Some(v) => {
                format!(
                    "\"{}\" by {} ({}). {} — {}",
                    self.title, self.authors, year_str, v, self.url
                )
            }
            None => {
                format!(
                    "\"{}\" by {} ({}). {}",
                    self.title, self.authors, year_str, self.url
                )
            }
        }
    }
}

// ─── Finding ─────────────────────────────────────────────────────────────────

/// The canonical output of research-radar and the primary input contract for evolve.
///
/// A Finding is *not* raw research output — it is an evaluated, prioritized signal
/// that has passed through radar's scoring pipeline and carries enough metadata for
/// evolve to make a decision.
///
/// ## Schema evolution
///
/// The `schema_version` field follows semver. Consumers MUST gracefully handle
/// unknown fields (they will be ignored during serde). A consumer on version 1.0
/// receiving a 1.x Finding should parse it without error; fields it doesn't
/// understand are silently dropped.
///
/// Breaking changes (removing or renaming fields, changing semantics) require a
/// major version bump and a migration path.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Finding {
    /// Stable URN identifying this finding. Use this for deduplication and replay.
    pub id: String,

    /// URL of the source this finding was derived from.
    pub source_url: String,

    /// Title of the source (page title, paper title, etc.).
    pub source_title: String,

    /// Kind of source.
    pub source_type: super::SourceType,

    /// Functional domain this finding belongs to.
    ///
    /// Used by evolve to scope applicability searches. Examples:
    /// "rust", "distributed-systems", "ml-ops", "security", "web-performance"
    pub domain: String,

    /// Concise headline for this finding. Aim for one line.
    ///
    /// This is what appears in the evolve queue and PR title.
    pub title: String,

    /// 2–4 sentence plain-English summary of *what* was found and *why* it matters.
    ///
    /// Written for a senior engineer reading a PR description. Not raw abstract.
    pub summary: String,

    /// How confident radar is that this finding is real and correctly scored.
    ///
    /// 0.0 = speculation / very low confidence.
    /// 1.0 = very high confidence (e.g. CVE from NVD, confirmed benchmark regression).
    ///
    /// Used by evolve to filter before proposing. A finding with confidence < 0.4
    /// should be treated as a candidate, not a driver.
    pub confidence: f32,

    /// How much this finding would change the codebase if acted on.
    ///
    /// 0.0 = cosmetic, purely additive, no behavior change.
    /// 1.0 = fundamental: changes core assumptions, affects many call sites,
    ///       or alters published APIs.
    ///
    /// Used by evolve to scope the diff and by humans reviewing the queue to
    /// calibrate review time.
    pub impact_weight: f32,

    /// 0.0 = identical to a prior finding; 1.0 = maximally novel (no similar prior).
    /// Computed as 1.0 - max cosine similarity vs prior finding embeddings.
    #[serde(default)]
    pub novelty_score: f32,

    /// Urgency classification. Determines queue priority.
    ///
    /// Critical = CVE, active exploit, severe regression → evolve should flag
    ///             this immediately rather than waiting for a scheduled run.
    /// High     = significant issue that should land soon.
    /// Medium   = normal priority.
    /// Low      = background improvement, not urgent.
    pub urgency: UrgencyLevel,

    /// High-level suggested action for evolve. Not a diff — an intent.
    ///
    /// Examples:
    /// - "Refactor async task spawning to use tokio::spawn with proper JoinSet"
    /// - "Replace Arc<Mutex<T>> with tokio::sync::RwLock in hot path"
    /// - "Adopt structured concurrency pattern from paper Section 3.2"
    /// - "Update tokio version constraint to >= 1.40 to pick up fixes"
    ///
    /// evolve is responsible for generating the specific diff from this intent
    /// plus an applicability search against the codebase.
    pub suggested_action: String,

    /// Real LLM-evaluated hypothesis of how this finding applies to the target system.
    ///
    /// Empty when evaluation has not been run.
    #[serde(default)]
    pub applicability_hypothesis: String,

    /// Optional concrete experiment evolve could run to validate applicability.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub suggested_experiment: Option<String>,

    /// Freeform tags for filtering the evolve queue and scoping applicability.
    ///
    /// Examples: "async-runtime", "memory-safety", "tokio", "lock-free",
    ///           "cve", "performance", "api-design"
    pub applicability_tags: Vec<String>,

    /// Formal citation for the source this finding is based on.
    ///
    /// None if the finding is derived from non-paper sources (e.g. a blog post
    /// or direct benchmark) and a formal citation isn't meaningful.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cited_paper: Option<PaperRef>,

    /// When radar surfaced this finding.
    pub discovered_at: DateTime<Utc>,

    /// IDs of radar Entry records that contributed to this finding.
    ///
    /// Allows tracing a Finding back to the raw annotated content that generated it.
    /// Useful for debugging scoring and for human review of radar quality.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub related_entry_ids: Vec<String>,

    /// Schema version of this Finding. Currently "1.0".
    ///
    /// Consumers MUST accept minor-version-forward changes without error.
    pub schema_version: String,
}

impl Finding {
    /// Construct a new Finding with the given required fields.
    ///
    /// id, discovered_at, and schema_version are set automatically.
    /// confidence defaults to 0.5. urgency defaults to Medium.
    /// impact_weight defaults to 0.5.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        source_url: String,
        source_title: String,
        source_type: super::SourceType,
        domain: String,
        title: String,
        summary: String,
        suggested_action: String,
        applicability_tags: Vec<String>,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            source_url,
            source_title,
            source_type,
            domain,
            title,
            summary,
            confidence: 0.5,
            impact_weight: 0.5,
            novelty_score: 0.0,
            urgency: UrgencyLevel::Medium,
            suggested_action,
            applicability_hypothesis: String::new(),
            suggested_experiment: None,
            applicability_tags,
            cited_paper: None,
            discovered_at: Utc::now(),
            related_entry_ids: Vec::new(),
            schema_version: String::from("1.0"),
        }
    }

    /// Set the novelty score (0.0..=1.0). Returns self for chaining.
    pub fn with_novelty_score(mut self, novelty: f32) -> Self {
        self.novelty_score = novelty;
        self
    }

    /// Attach an evaluated applicability hypothesis (and optional suggested experiment).
    pub fn with_applicability(
        mut self,
        hypothesis: String,
        suggested_experiment: Option<String>,
    ) -> Self {
        self.applicability_hypothesis = hypothesis;
        self.suggested_experiment = suggested_experiment;
        self
    }

    /// Whether this finding is severe enough to warrant immediate action.
    ///
    /// Convenience shorthand for `urgency.is_critical()` or `confidence == 1.0`.
    pub fn is_critical(&self) -> bool {
        self.urgency.is_critical() || self.confidence >= 0.95
    }

    /// Whether evolve should consider this finding actionable.
    ///
    /// Confidence must be above the minimum threshold AND urgency must be at least Low.
    pub fn is_actionable(&self) -> bool {
        self.confidence >= 0.4 && self.urgency != UrgencyLevel::Low
    }

    /// Priority score for queue sorting.
    ///
    /// Combines urgency tier, confidence, and impact weight into a single float.
    /// Higher = more urgent. Used to rank the evolve queue.
    ///
    /// Formula: (urgency_tier * 0.5) + (confidence * 0.3) + (impact_weight * 0.2)
    /// Urgency tiers: Low=1, Medium=2, High=3, Critical=4
    pub fn priority_score(&self) -> f32 {
        let urgency_tier = match self.urgency {
            UrgencyLevel::Low => 1.0,
            UrgencyLevel::Medium => 2.0,
            UrgencyLevel::High => 3.0,
            UrgencyLevel::Critical => 4.0,
        };
        (urgency_tier * 0.5) + (self.confidence * 0.3) + (self.impact_weight * 0.2)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn finding_new_sets_defaults() {
        let f = Finding::new(
            "https://example.com/paper".into(),
            "Example Paper".into(),
            super::super::SourceType::Paper,
            "rust".into(),
            "Tokio spawn pattern".into(),
            "A better pattern for spawning tasks.".into(),
            "Refactor to use JoinSet".into(),
            vec!["async-runtime".into()],
        );

        assert_eq!(f.schema_version, "1.0");
        assert_eq!(f.confidence, 0.5);
        assert_eq!(f.impact_weight, 0.5);
        assert_eq!(f.novelty_score, 0.0);
        assert_eq!(f.urgency, UrgencyLevel::Medium);
        assert!(!f.is_critical());
        assert!(f.is_actionable());
        assert!(!f.id.is_empty());
    }

    #[test]
    fn with_novelty_score_sets_field() {
        let f = Finding::new(
            "https://example.com/paper".into(),
            "Example Paper".into(),
            super::super::SourceType::Paper,
            "rust".into(),
            "Tokio spawn pattern".into(),
            "A better pattern for spawning tasks.".into(),
            "Refactor to use JoinSet".into(),
            vec!["async-runtime".into()],
        )
        .with_novelty_score(0.7);

        assert_eq!(f.novelty_score, 0.7);
    }

    #[test]
    fn critical_finding_is_actionable() {
        let mut f = Finding::new(
            "https://example.com/cve".into(),
            "CVE-2024-9999".into(),
            super::super::SourceType::Web,
            "security".into(),
            "Critical vulnerability in crate X".into(),
            "Remote code execution via malformed input.".into(),
            "Update crate X to >= 2.1.0".into(),
            vec!["cve".into()],
        );
        f.urgency = UrgencyLevel::Critical;
        f.confidence = 0.99;

        assert!(f.is_critical());
        assert!(f.is_actionable());
    }

    #[test]
    fn low_confidence_is_not_actionable() {
        let mut f = Finding::new(
            "https://example.com/speculation".into(),
            "Random Blog Post".into(),
            super::super::SourceType::Article,
            "rust".into(),
            "Maybe consider this pattern".into(),
            "Someone suggested something.".into(),
            "Consider adopting this pattern".into(),
            vec![],
        );
        f.confidence = 0.2;
        f.urgency = UrgencyLevel::Low;

        assert!(!f.is_actionable());
    }

    #[test]
    fn priority_score_orders_correctly() {
        let mut low = Finding::new(
            "https://low.example".into(),
            "Low".into(),
            super::super::SourceType::Web,
            "rust".into(),
            "Low".into(),
            "Summary.".into(),
            "Action".into(),
            vec![],
        );
        low.urgency = UrgencyLevel::Low;
        low.confidence = 0.3;
        low.impact_weight = 0.2;

        let mut critical = Finding::new(
            "https://critical.example".into(),
            "Critical".into(),
            super::super::SourceType::Web,
            "security".into(),
            "Critical".into(),
            "Summary.".into(),
            "Action".into(),
            vec![],
        );
        critical.urgency = UrgencyLevel::Critical;
        critical.confidence = 0.95;
        critical.impact_weight = 0.9;

        assert!(critical.priority_score() > low.priority_score());
    }

    #[test]
    fn paper_ref_citation_format() {
        let paper = PaperRef::new(
            "Memory Safety Without Runtime Overhead".into(),
            "Carl Hensel, Patrik Wirth".into(),
            "https://example.com/paper".into(),
        );

        let cit = paper.citation();
        assert!(cit.contains("Memory Safety Without Runtime Overhead"));
        assert!(cit.contains("Carl Hensel"));
        assert!(cit.contains("n.d.")); // no year set, falls back to n.d.
    }

    #[test]
    fn paper_ref_citation_with_year_and_venue() {
        let mut paper = PaperRef::new(
            "Formal Verification for the Rest of Us".into(),
            "Jane Doe".into(),
            "https://example.com/paper".into(),
        );
        paper.year = Some(2024);
        paper.venue = Some("SOSP".into());

        let cit = paper.citation();
        assert!(cit.contains("2024"));
        assert!(cit.contains("SOSP"));
    }

    #[test]
    fn finding_serde_roundtrip() {
        let mut f = Finding::new(
            "https://example.com/paper".into(),
            "Example Paper".into(),
            super::super::SourceType::Paper,
            "rust".into(),
            "Tokio spawn pattern".into(),
            "A better pattern for spawning tasks.".into(),
            "Refactor to use JoinSet".into(),
            vec!["async-runtime".into()],
        )
        .with_applicability(
            "applies to async runtime".into(),
            Some("benchmark JoinSet vs raw spawn".into()),
        );
        f.cited_paper = Some(PaperRef::new(
            "Formal Concurrency".into(),
            "Carl Hensel".into(),
            "https://example.com/paper".into(),
        ));
        f.related_entry_ids = vec!["entry-1".into(), "entry-2".into()];

        // Deserialize via Value to avoid serde_json lifetime inference issues in tests
        let json_bytes = serde_json::to_vec(&f).expect("serialization succeeds");
        let value: serde_json::Value =
            serde_json::from_slice(&json_bytes).expect("json parse succeeds");
        let parsed: Finding = serde_json::from_value(value).expect("finding deserialize succeeds");

        assert_eq!(parsed.id, f.id);
        assert_eq!(parsed.title, f.title);
        assert_eq!(
            parsed.cited_paper.as_ref().unwrap().title,
            "Formal Concurrency"
        );
        assert_eq!(parsed.applicability_hypothesis, f.applicability_hypothesis);
        assert_eq!(parsed.suggested_experiment, f.suggested_experiment);
        assert_eq!(parsed.related_entry_ids.len(), 2);
        assert_eq!(parsed.schema_version, "1.0");
    }
}
